### ISSUE TITLE
Question on cumulative LID calculation

### ISSUE THREAD

**Issue by franciszchen** [Xu-Jingyi/FedCorr#1]
Hi JIngyi, thanks for sharing this great work! Sorry that I am a little confused about the LID calculation and have some issues to verify. 

1. In https://github.com/Xu-Jingyi/FedCorr/blob/95a3c7ac1dffbcdf67ef278ae09237b195941f64/main.py#L100, with default args.frac1=0.01, does it mean the LID is cumulated for 100 times? I am wondering if it is necessary to perform so many times, and is Fig.3 in the paper also plotted with 100 times accumulation?  
2. Another question is, it seems the global model parameters are updated during the LID accumulation, as https://github.com/Xu-Jingyi/FedCorr/blob/95a3c7ac1dffbcdf67ef278ae09237b195941f64/main.py#L134? Would this affect the performance of the framework?

**Comment by Xu-Jingyi** [comment]
Hi Francis, 

Thank you for reading our paper and providing your valuable comments!

1. In our experiment setting, we set default frac1=0.01 and iteration1=5, which informally means that we go through all 100 clients 5 times. The LID score **for each client** is only calculated after its local training, when this client is selected by the server. Hence in the experiment, we only cumulate the LID score of each client for 5 times (totally 100 clients * 5 times), which is consistent with the results shown in Fig.3.

2. The calculation and accumulation of LID don't affect the aggregation process. In fact, LID is just a measurement of the "dimension" of the prediction space for a given model (with fixed weights) and a given dataset, hence it won't be involved in the weights updating steps.

Hope this can answer your questions. Do let me know if you have any further queries.
