### ISSUE TITLE
A puzzle on the settings of non-IID hyperparameters on CIFAR-100

### ISSUE THREAD

**Issue by lijichang** [Xu-Jingyi/FedCorr#2]
Hi, Jingyi.
Many thanks for your excellent work.

But, I have a puzzle about how \rho and \tau are set for non-IID hyperparameters on CIFAR-100.  I have read and found that the caption description of Table 3 in the supplementary document submitted by you on the official CVPR website is (\rho, \tau)=(0.4, 0) respectively, but your body description is (0.4, 0.5), which makes me confused.  Since the code you submitted fails to clearly explain your experimental parameter settings, I would like to ask you about it. 

I am looking forward to your reply. Thank you very much again.

Below is the link to the supplementary on the CVPR website.
https://openaccess.thecvf.com/content/CVPR2022/supplemental/Xu_FedCorr_Multi-Stage_Federated_CVPR_2022_supplemental.pdf

**Comment by Xu-Jingyi** [comment]
Hi Jichang,

Thank you for reading our paper and pointing out our typo!

We have checked our experiments record, the actual noise level for CIFAR-100 with non-IID partition is $(\rho, \tau)$=(0.4, 0).

Hope this can answer your question. Do let me know if you have any further queries.

**Comment by lijichang** [comment]
Many thanks.
